In [1]:
import csv
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

from os.path import join

import tensorflow as tf 
from tensorflow.keras import layers, models, optimizers
from tensorflow.keras.utils import to_categorical

In [4]:
a = np.random.rand(10000,1600,4)

In [7]:
b = np.where(a < 0.5, 0, a)
c = np.where(b >= 0.5, 1, b)

In [8]:
print(c)

[[[0. 1. 0. 0.]
  [0. 0. 1. 1.]
  [1. 1. 0. 1.]
  ...
  [0. 0. 0. 0.]
  [1. 1. 1. 1.]
  [0. 0. 0. 1.]]

 [[1. 0. 1. 0.]
  [1. 0. 0. 0.]
  [1. 1. 0. 0.]
  ...
  [1. 1. 1. 0.]
  [0. 1. 1. 1.]
  [0. 0. 0. 1.]]

 [[0. 0. 0. 0.]
  [0. 0. 1. 1.]
  [1. 0. 0. 1.]
  ...
  [0. 1. 0. 1.]
  [1. 1. 0. 1.]
  [1. 1. 1. 0.]]

 ...

 [[1. 0. 1. 0.]
  [1. 0. 0. 0.]
  [0. 1. 1. 0.]
  ...
  [1. 0. 1. 0.]
  [0. 1. 1. 1.]
  [1. 1. 0. 1.]]

 [[0. 0. 0. 1.]
  [1. 1. 1. 0.]
  [0. 0. 1. 0.]
  ...
  [1. 0. 1. 0.]
  [0. 0. 0. 0.]
  [1. 0. 0. 0.]]

 [[0. 1. 1. 0.]
  [1. 1. 0. 1.]
  [1. 1. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [0. 1. 1. 1.]]]


In [9]:
np.save('RandomData01.npy',c)